---
info:
  title: Controls Rb
  description: ControlsInsight Ruby client
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/controls.rb
  x-cortex-tag: controls-rb
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: threatintel-rd
openapi: 3.0.1
servers:
- url: "/"
